export const colors = {
  italyGreen: '#009246',
  italyWhite: '#FFFFFF',
  italyRed: '#CE2B37',
  /** Intro / splash screen */
  splashLightYellow: '#ecf7c3',
  background: '#FAFAFA',
  surface: '#FFFFFF',
  textPrimary: '#1A1A1A',
  textSecondary: '#5C5C5C',
  textMuted: '#8E8E8E',
  border: '#E8E8E8',
  shadow: 'rgba(26, 26, 26, 0.08)',
  accentGreen: '#0D6B4A',
  star: '#C4A035',
  mapWater: '#C8D9E8',
  mapPark: '#D4E8DC',
  mapRoad: '#F0EDE8',
  mapPin: '#0D6B4A',
  stageBg: '#141414',
  /** Favorites tier badges — distinct bronze / silver / gold */
  tierBronze: '#A65D2E',
  tierBronzeBg: '#FFF4EB',
  tierBronzeBorder: '#CD853F',
  tierSilver: '#5C6B73',
  tierSilverBg: '#EEF2F5',
  tierSilverBorder: '#9AA5AD',
  tierGold: '#B8860B',
  tierGoldBg: '#FDF8E6',
  tierGoldBorder: '#D4AF37',
} as const;
